"""
Modelica model template generator.

Generates skeleton Modelica models (as plain-text strings) for common
HVAC topologies.  These can be saved as ``.mo`` files and opened in
tools like OpenModelica or Dymola.
"""

from __future__ import annotations


def heat_pump_model(
    name: str = "HeatPumpSystem",
    hp_power_kw: float = 10.0,
    buffer_volume_m3: float = 0.5,
    supply_temp_c: float = 45.0,
) -> str:
    """Generate a basic Modelica model for a heat-pump system.

    Parameters
    ----------
    name : str
        Model name (Modelica identifier).
    hp_power_kw : float
        Nominal heating capacity in kW.
    buffer_volume_m3 : float
        Buffer tank volume in m³.
    supply_temp_c : float
        Design supply temperature in °C.

    Returns
    -------
    str
        Modelica source code.
    """
    return f"""\
model {name}
  "Air-source heat pump system — auto-generated by ai-hvac"

  // ---- Parameters ----
  parameter Modelica.Units.SI.Power Q_nom = {hp_power_kw * 1000}
    "Nominal heating capacity [W]";
  parameter Modelica.Units.SI.Volume V_buf = {buffer_volume_m3}
    "Buffer tank volume [m³]";
  parameter Modelica.Units.SI.Temperature T_supply = {supply_temp_c + 273.15}
    "Design supply temperature [K]";

  // ---- Components ----
  // TODO: Replace placeholders with AixLib / Buildings library components
  // AixLib.Fluid.HeatPumps.HeatPump heatPump(...);
  // AixLib.Fluid.Storage.StratifiedEnhanced buffer(...);
  // AixLib.Fluid.Sources.Boundary_pT boundary(...);

  // ---- Connections ----
  // connect(heatPump.port_b, buffer.port_a);
  // connect(buffer.port_b, building.port_a);

equation
  // Placeholder equation block
  // Add control logic and energy balance equations here

  annotation (
    Documentation(info="<html>
      <p>Auto-generated heat pump system model.</p>
      <p>Replace placeholder components with library models from
      <a href=\\"https://github.com/RWTH-EBC/AixLib\\">AixLib</a> or
      <a href=\\"https://simulationresearch.lbl.gov/modelica/\\">Buildings</a>.
      </p>
    </html>"),
    experiment(
      StopTime = 31536000,
      Interval = 3600,
      Tolerance = 1e-06
    )
  );
end {name};
"""


def district_heating_model(
    name: str = "DistrictHeatingSubstation",
    design_power_kw: float = 50.0,
) -> str:
    """Generate a basic Modelica model for a district heating substation.

    Parameters
    ----------
    name : str
        Model name (Modelica identifier).
    design_power_kw : float
        Design heating capacity in kW.

    Returns
    -------
    str
        Modelica source code.
    """
    return f"""\
model {name}
  "District heating substation — auto-generated by ai-hvac"

  parameter Modelica.Units.SI.Power Q_design = {design_power_kw * 1000}
    "Design heating capacity [W]";
  parameter Modelica.Units.SI.Temperature T_supply = 343.15
    "Supply temperature [K] (70 °C)";
  parameter Modelica.Units.SI.Temperature T_return = 313.15
    "Return temperature [K] (40 °C)";

equation
  // Placeholder — add heat exchanger, control valve, and building load

  annotation (
    Documentation(info="<html>
      <p>District heating substation model.</p>
    </html>")
  );
end {name};
"""
